### ISSUE TITLE
[feat] : 뉴스상세페이지 쉬운해설 파트 기능 구현

### ISSUE THREAD

**Issue by jinaaaaaaaaaaaaa** [2024-Fall-CapstoneDesign/newReals_FE#55]
## Description
어떤 작업에 관한 이슈 인가요?

뉴스상세페이지 쉬운해설 파트 기능 구현

## Todo
- [ ] 뉴스상세페이지 쉬운해설 파트 UI 구현
- [ ] 용어 클릭시 해설 뜨는 기능
- [ ] 원본 뉴스 연결

## ETC
기타 사항
