### ISSUE TITLE
[feat] : 프로필 페이지 API 연동

### ISSUE THREAD

**Issue by yeona813** [2024-Fall-CapstoneDesign/newReals_FE#76]
## Description
어떤 작업에 관한 이슈 인가요?
프로필 페이지 API 연동

## Todo
- [ ] 프로필 정보 조회
- [ ] 출석 현황 조회
- [ ] 스크랩 뉴스 리스트
- [ ] 스크랩 뉴스 검색
- [ ] 관심사 분석 기본
- [ ] 프로필 정보 수정
- [ ] 프로필에서 스크랩 해제
- [ ] 관심사 분석 레포트

## ETC
기타 사항
