### ISSUE TITLE
[feat] : 뉴스 상세페이지 api 연동

### ISSUE THREAD

**Issue by jinaaaaaaaaaaaaa** [2024-Fall-CapstoneDesign/newReals_FE#87]
## Description
어떤 작업에 관한 이슈 인가요?

뉴스 상세페이지 api 연동

## Todo
- [ ] 뉴스 기사 api 연동
- [ ] 퀴즈 api 연동
- [ ] 인사이트 api 연동

## ETC
기타 사항
